substitutions:
  device_name: controlsr
  room: p0
  ip: 192.168.1.48
  gateway: 192.168.1.1
  dns: 192.168.1.1
  subnet: 255.255.255.0
  addr1: "0x369951e90264ff28"
  addr2: "0xe7f53de90264ff28"
  
#### general for esphome
  web_password: !secret tasmota_password
  web_user: !secret tasmota_user
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  ota_password: !secret ota_password   
  ap_password: !secret tasmota_password


esphome:
  name: ${device_name}${room}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino


# Enable logging
logger:

api:


# ESP Restart button
button:
  - platform: restart
    name: ${device_name}${room} restart 
    id: restart_${device_name}${room}

ota:
  password: $ota_password

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  #fast_connect: on
  manual_ip:
    static_ip: $ip
    gateway: $gateway
    subnet: $subnet
    dns1: $dns

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}_$room
    password: $ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: ${web_user}
    password: ${web_password}

dallas:
  - pin: GPIO5
    update_interval: 10s